[build]
  command = "echo 'hey'"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  functions = "netlify-functions"
  functionsPort = 3000
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 404

[functions]
  included_files = ["dist/**/*"]

[[headers]]
  for = "/dist/functions/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
